example:
  config:
    one: "test"
    two: "test 2"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/new_db
    username: postgres
    password: pfvpfg,en072000
    driver-class-name: org.postgresql.Driver

liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yaml"